config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ratings
  scope '/api'do
    get '/ratings.json' => 'ratings#index'
    post '/ratings.json' => 'ratings#create'
    scope '/ratings' do
      #get '/:id/edit.json' => 'ratings#edit'
      get '/:id/show.json'=> 'ratings#show'
      put '/:id/edit.json' => 'ratings#edit'
      delete '/:id/destroy.json'=> 'ratings#destroy'
    end
  end
  root "ratings#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
    require 'rest-client'

    API_BASE_URL = "http://localhost:3000/api"

    def index
        uri = "#{API_BASE_URL}/ratings.json"
        rest_resource = RestClient::Resource.new(uri)
        ratings = rest_resource.get
        @ratings = JSON.parse(ratings, :symbolize_names => true)        
    end

    def new
    end

    def create
        uri = "#{API_BASE_URL}/ratings"
        payload = params.to_json(:only => [:rating, :idMovie])
        rest_resource = RestClient::Resource.new(uri)
        begin
            rest_resource.post payload , :content_type => "application/json"
            flash[:notice] = "Rating saved successfully"
        rescue Exception => e
            flash[:error] = "Rating failed to save"
        end
        redirect_to root_path
    end

   # def edit
    #    uri = "#{API_BASE_URL}/ratings/#{params[:id]}/edit.json"
     #   rest_resource = RestClient::Resource.new(uri)
      #  ratings = rest_resource.get
       # @rating = JSON.parse(ratings, :symbolize_names => true)
    #end

    def edit
        uri = "#{API_BASE_URL}/ratings/#{params[:id]}/edit.json"
	    payload = params.to_json(:only => [:rating])
	    rest_resource = RestClient::Resource.new(uri)
	    begin
	      rest_resource.put payload , :content_type => "application/json"
	      flash[:notice] = "Rating updated successfully"
	    rescue Exception => e
	      flash[:error] = "Raiting failed to update"
	    end
	    redirect_to root_path
    end
      
    def destroy
        uri = "#{API_BASE_URL}/ratings/#{params[:id]}/destroy.json"
	    rest_resource = RestClient::Resource.new(uri)
	    begin
	     rest_resource.delete
	     flash[:notice] = "Rating deleted successfully"
	    rescue Exception => e
	     flash[:error] = "Rating failed to delete"
	    end
	    redirect_to root_path
	end
	 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiClient</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ratings/edit.html.erb
<%= form_tag edit_rating_path, :method => :put do %>
    rating : <%=text_field_tag :rating, @rating[:rating]%><br />
    <%=submit_tag "update"%>
 <%end%>

app/views/ratings/index.html.erb
<%= link_to "Create New Rating", new_rating_path %>
<p>List of Ratings</p>
<table width="100%">
	<tr>
	  <td>Movie</td>
	  <td>Rating</td>
	  <td>Action</td>
	</tr>
	<% @ratings.each do |r|%>
	  <tr>
	    <td><%=r[:title]%></td>
	    <td><%=r[:rating]%></td>
	    <td>
	      <%= link_to "Edit", edit_rating_path(r[:id]) %> | 
	      <%= link_to "Delete", rating_path(r[:id]), :method => :delete %>
	    </td>
		</tr>
	<% end %>
</table>

app/views/ratings/new.html.erb
<%= form_tag ratings_path, :method => :post do %>
    idMovie : <%=text_field_tag :idMovie%>
    <br>
    rating : <%=text_field_tag :rating%>
    <br>
    <%=submit_tag "save"%>
<%end%>